# 异常

Java 中错误分为两类：

- **编译时错误**（语法错误）

- **运行时错误** （用异常类来描述错误）



## 异常类

异常类（Throwable）包括：Error 和 Exception

Error：指系统错误，JVM生成，程序**无法处理**

Exception：程序运行期间出现的错误，程序**可以处理**

![1614852510822](C:\Users\86185\AppData\Roaming\Typora\typora-user-images\1614852510822.png)

**Exception一般又分为 Checked异常（左支）和非Checked异常（右支）**

- **Checked异常** 

Java程序**必须**显示处理Checked异常 

我们比较熟悉的Checked异常有：ClassNotFoundException、NoSuchMetodException、IOException

- **非Checked异常**

由系统**自动检测**也可以根据需求**手动处理**

一般是 RuntimeException 及其子类

![1621695429622](C:\Users\86185\AppData\Roaming\Typora\typora-user-images\1621695429622.png)





## JAVA内置异常类

非Checked异常：

| **异常**                        | **描述**                                                     |
| ------------------------------- | ------------------------------------------------------------ |
| ArithmeticException             | 当出现异常的运算条件时，抛出此异常。例如，一个整数"除以零"时，抛出此类的一个实例。 |
| ArrayIndexOutOfBoundsException  | 用非法索引访问数组时抛出的异常。如果索引为负或大于等于数组大小，则该索引为非法索引。 |
| ArrayStoreException             | 试图将错误类型的对象存储到一个对象数组时抛出的异常。         |
| ClassCastException              | 当试图将对象强制转换为不是实例的子类时，抛出该异常。         |
| IllegalArgumentException        | 抛出的异常表明向方法传递了一个不合法或不正确的参数。         |
| IllegalMonitorStateException    | 抛出的异常表明某一线程已经试图等待对象的监视器，或者试图通知其他正在等待对象的监视器而本身没有指定监视器的线程。 |
| IllegalStateException           | 在非法或不适当的时间调用方法时产生的信号。换句话说，即 Java 环境或 Java 应用程序没有处于请求操作所要求的适当状态下。 |
| IllegalThreadStateException     | 线程没有处于请求操作所要求的适当状态时抛出的异常。           |
| IndexOutOfBoundsException       | 指示某排序索引（例如对数组、字符串或向量的排序）超出范围时抛出。 |
| NegativeArraySizeException      | 如果应用程序试图创建大小为负的数组，则抛出该异常。           |
| NullPointerException            | 当应用程序试图在需要对象的地方使用 `null` 时，抛出该异常     |
| NumberFormatException           | 当应用程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式时，抛出该异常。 |
| SecurityException               | 由安全管理器抛出的异常，指示存在安全侵犯。                   |
| StringIndexOutOfBoundsException | 此异常由 `String` 方法抛出，指示索引或者为负，或者超出字符串的大小。 |
| UnsupportedOperationException   | 当不支持请求的操作时，抛出该异常。                           |



Checked异常：

| **异常**                   | **描述**                                                     |
| -------------------------- | ------------------------------------------------------------ |
| ClassNotFoundException     | 应用程序试图加载类时，找不到相应的类，抛出该异常。           |
| CloneNotSupportedException | 当调用 `Object` 类中的 `clone` 方法克隆对象，但该对象的类无法实现 `Cloneable` 接口时，抛出该异常。 |
| IllegalAccessException     | 拒绝访问一个类的时候，抛出该异常。                           |
| InstantiationException     | 当试图使用 `Class` 类中的 `newInstance` 方法创建一个类的实例，而指定的类对象因为是一个接口或是一个抽象类而无法实例化时，抛出该异常。 |
| InterruptedException       | 一个线程被另一个线程中断，抛出该异常。                       |
| NoSuchFieldException       | 请求的变量不存在                                             |
| NoSuchMethodException      | 请求的方法不存在                                             |



## 异常方法

下面的列表是 Throwable 类的主要方法:

| **序号** | **方法及说明**                                               |
| -------- | ------------------------------------------------------------ |
| 1        | **public String getMessage()** ：返回关于发生的异常的详细信息。这个消息在Throwable 类的构造函数中初始化了。 |
| 2        | **public Throwable getCause()** ：返回一个Throwable 对象代表异常原因。 |
| 3        | **public String toString()** ：使用getMessage()的结果返回类的串级名字。 |
| 4        | **public void printStackTrace()** ：打印toString()结果和栈层次到System.err，即错误输出流。 |
| 5        | **public StackTraceElement [] getStackTrace()** ：返回一个包含堆栈层次的数组。下标为0的元素代表栈顶，最后一个元素代表方法调用堆栈的栈底。 |
| 6        | **public Throwable fillInStackTrace()** ：用当前的调用栈层次填充Throwable 对象栈层次，添加到栈层次任何先前信息中。 |



## 异常语法

- try-catch-finally

```java
try{
    可能抛出异常的代码
}catch(){
    处理异常		   //可以多次使用
}finally{
    最终要执行的代码	//注意在此之前存在 return、exit等情况			
}
```

（1）**finally 的优先级比 return 高**

（2）**finally  的优先级比 exit(0) 低**



- ## throw 和 throws

**throw**：开发者主动抛出异常（作用于具体的**逻辑代码**）

```java
throw new 异常类()
```

**throws**：方法可能会抛出的异常（作用于**方法**）

```java
public 方法类型 方法名（参数列表）throws 异常类{
}
```

**如果 throws 的异常类是 RuntimeException 或者其子类，外部调用可以不处理，JVM会自动处理**

**如果 throws 的异常类是 Exception 或者是其子类中的Checked异常，外部调用必须处理，不然会报错**



## 异常处理方式

① try-catch  

②继续抛出异常（**throws**）



## 自定义异常

```java
public class MyError extends Throwable{
    public MyError(String message) {
        super(message);
    }

    public static void main(String[] args) throws MyError {
        throw new MyError("自定义异常");
    }
}
```







